#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
REQUIRES='core'
DESCRIPTION='VNC-based tabbed X11 install. Replaces X11 if specified first.'
CHROOTBIN='croutonxinitrc-wrapper xinit'
# Prevent X11 from being added if it hasn't already.
echo 'x11' >> "${TARGETDEDUPFILE:-/dev/null}"
. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:
apt-get -y --no-install-recommends install \
    vnc4server dmz-cursor-theme xterm xfonts-base

# Modify xserverrc
echo '#!/bin/sh -e
exec /usr/bin/Xvnc -DeferUpdate 10 -NeverShared -SecurityTypes none -IdleTimeout 0 -localhost -once "$@"
' > /etc/X11/xinit/xserverrc

NOCROUTONPOWERD='y'
### append x11-common
